# Generated by Django 5.0.7 on 2024-08-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField()),
                ('dealHOD', models.CharField(max_length=30)),
                ('coordinator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ryear', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('currentrole', models.CharField(max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('pmembers', models.CharField(max_length=100)),
                ('pdescription', models.CharField(max_length=300)),
                ('pguide', models.CharField(max_length=20)),
                ('pdomain', models.CharField(max_length=40)),
                ('pyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.year')),
            ],
        ),
    ]
