# Generated by Django 5.0.7 on 2024-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_register_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='pyear',
            field=models.CharField(max_length=5),
        ),
    ]
